on: push

jobs:
  sea-action:
    name: Build SEA
    strategy:
      matrix: { dir: ['./javaumltranslator'], os: [ubuntu-latest] }
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ matrix.dir }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - run: pwd

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.0

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Find Node
        id: find-node
        run:
          echo "node=$(node -e 'console.log(process.argv[0]);')" >>
          $env:GITHUB_OUTPUT

      - name: SEA
        id: sea
        uses: bryopsida/node-sea-action@v1
        with:
          working-dir: ${{ matrix.dir }}
          output-dir: build
          executable-name: umltojava
          sea-config-path: sea-config.json
          node-path: ${{ steps.find-node.outputs.node }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-sea
          path: build/
          if-no-files-found: error