name: "JavaUMLTranslator - Binaries (SEA)"
on: 
  workflow_dispatch:

jobs:
  sea-trigger-umltojava:
    uses: ./.github/workflows/sea.yml
    with:
      projectFolder: ./javaumltranslator
      commandPath: ./javaumltranslator/dist/cli/umlToJavaCLI.js
      commandName: umlToJava
      
  sea-trigger-javaToUml:
    uses: ./.github/workflows/sea.yml
    with:
      projectFolder: ./javaumltranslator
      commandPath: ./javaumltranslator/dist/cli/javaToUmlCLI.js
      commandName: javaToUml
