name: Generate VSIX # Rename to "Publish VSIX" when extensions will be public

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Select one project to build VSIX'
        required: true
        default: 'javaumltranslator'
        type: choice
        options:
          - javaumltranslator
          - protobufumltranslator

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.project }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version: 24.x

      - name: Install Datamodel's dependencies
        run: npm install
        working-directory: ./datamodel

      - name: Build Datamodel project
        run: npm run build
        working-directory: ./datamodel

      - name: Install dependencies
        run: npm install

      - name: Test Project
        run: npm test

      - name: Generate Extension VSIX
        run: npm run package

      - uses: actions/upload-artifact@v6
        with:
          name: ${{ inputs.project }}.vsix
          path: ${{ inputs.project }}/${{ inputs.project }}.vsix
          if-no-files-found: error
